#!/usr/bin/env python3

""" Problem
An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.

Given: A DNA string t having length at most 1000 nt.

Return: The transcribed RNA string of t.

Sample Dataset
GATGGAACTTGACTACGTAAATT

Sample Output
GAUGGAACUUGACUACGUAAAUU

"""

__author__ = "T-Chinsky"
__copyright__ = "Copyright 2022"
__credits__ = ["T-Chinsky"]
__license__ = "MIT"
__version__ = "1.0.0"
__maintainer__ = "T-Chinsky"
__status__ = "Completed"

def transcribe(dna):
    """
    transcribes dna into rna
    :param dna: string of nucleotide bases
    :return: string of nucleotide bases for rna ('A','U','G','C')
    """
    rna = ""
    for i in dna:
        if i == 'T':
            rna += 'U'
        else:
            rna += i

    print(rna)

if __name__ == '__main__':
    dna = "CACCGGGCTGCCAGTGGAAACCCGGTGAATGAAGTACCAGGCGAGCGGACGGCTTCCTCTACCTCACTAAACTATTTTAAGAGGGAATGTCTGGCATAACGCCCGTATCACAAGAGCTACCATGCAACAGCTACACAAGCCGATCAACGCCCGAAGATTGAGTAGTGCTATACGAATGACGTAGCACTCTTGGGAGTGAGTCTAGTGTGGACTGTTTGACTGAAACATAAACCGTGAATGTCCACGATACCACGTGGTGCTCCGCTGCGGGTCCAGATTTCCTTCATTGCGATCCACTCTACGTCTGGGCGTGGCCTCGGGGAACCGGAGATACCTTACTGTAGCCCGCCAAAAATAAGAGTAACAGAGTACGGTGAGTCTAAAACGTGTAGTGGCATAACGTACATGAGGAGACCACTTCAGATGAGCGCACAAGGATTGCAGGTAAGGCTCAAAGAAGACCAACTTGTAGAGATGCTTGGTAGGGCCCGGATGGATCTATTTACAAATGGCTGTAGTTACAGGACCGTTCGGTGGCGCACCGGTGCCTGTAACGCCTTTTCCACTACCCCACACATAAATATAATTCAGTGAGCCCTGATCGACCCTCAGGTCGACCCGCCGTCCATTTAGGCCGCAAGGGTGTACAGAAATGTAATTAGGTTTACAAATTGGCCGTAATCAGATATTCGATACCCTATCGTCTGACCGCCCCAAGTCCTTAAAGATATGGGGAGTCCGTTCCCAAACGAGAAATTAAGGGATGAGGACGAGCCCTCGCGAGGTGAACCCTACGGATGGCGATCGCAGTGTATTCTGCACCTGCTAGGAAGGTAAGCGCAGTATTCTCCATGGCAGAGCGGGACACTGATCCAATCTACCCGCGTAATCGTGACGGCCCGGAACTCTCATCATGGGAATCACCGAGTGACATATGTGAATGAGATGTAAATTTCTTTAGGCGTAGGATGGCGGTCAAAAAGTACCACAAAGTA"
    transcribe(dna)
