#!/usr/bin/env python3

""" Problem

Given two strings s and t of equal length, the Hamming distance between s and t, denoted dH(s,t), is the number of corresponding symbols that differ in s and t. See Figure 2.

Given: Two DNA strings s and t of equal length (not exceeding 1 kbp).

Return: The Hamming distance dH(s,t).

Sample Dataset
GAGCCTACTAACGGGAT
CATCGTAATGACGGCCT

Sample Output
7

"""

__author__ = "T-Chinsky"
__copyright__ = "Copyright 2022"
__credits__ = ["T-Chinsky"]
__license__ = "MIT"
__version__ = "1.0.0"
__maintainer__ = "T-Chinsky"
__status__ = "Completed"

def pointMut(s1,s2):
    """
    take in two sequences of equal lengths and return all base mismatches (hamming distance)
    :param s1: sequence 1
    :param s2: sequence 2
    :return: integer of the hamming distance
    """
    hamming = 0

    if len(s1) != len(s2):
        print("strings are not of equal size")
    else:
        for i in range(len(s1)):
            if s1[i] != s2[i]:
                hamming += 1
    print(hamming)

if __name__ == '__main__':
    s1 = "TTTAGGGTACGCCGGGTATCGTGAGCTGCTTAAAAAAAACGAGCTATCCGGTCGATTTATGTACCCCCGAGTAACTCTTCTACATCGCGAACGTAGCAAGTGGACAGCAATCGAGGGCAGTGGTTAGTAAATAGGCTTTGCGTAGTGTGCGGTGCGCCGCGTAGGACATTACTACGCCTATTCCATTGACGCTAACAACTGGACGTACCTAAAGTTACTATAAACCCCAAGATGCTAGTTACTGATGGAGGTGCCCGAGTGAGACTATTCGCGCTCTTTATCTGGGGGAGGGACTAGAAATAGATTAGCTTTCAGAGGAGTCCGGAGCAATTCTGTAATCGATAGTCCCGTTTAGAACGTATCCGAAGGGTCGCTGGCGGCCTAAGGCTCCGCTCCACCGATCCGTGGTGTAATGAAAATACGCCGGAGGCTGTCTACCCTTCATCGGCCCCGGCAACGCATAGTTCTAGATAGAACGCACACGGTTACTAAATTATGTAGGGACGTATTCCGAATATCCGTCGCACCGAATATCAGGACACACCTCACCATCGGCGCAGTTGCCGAAAAGCCGGCCCGGGGGTAGATTTAATTCGTATCTAAGTCCATAGTAGGCTAAAGCTCGTCCAATTGTTCGAACTACCAGTAAAGGTGCGACTACGGGCCAGGATATCGGTGGATACCAGACTAGCCAGTTTGATGATCATCATAGCTACTATACTTAGCTGTCACTCTTGAGCATTCACTGCAGTGTCCGGTTCCCTTCCTGAGCCCAATATTGATGAAACGGGCGTAACGCCGTTGTATTTACTTCTTTGGCCTACCGCGTTTGCTTGTGATAGAGTGGATACGTACCTAGGAGTCCAGTAGAACGCTCGAGGCTGAGGCACCTGGTCGACACAGAATTGCCGCTT"
    s2 = "ACTCGAGGACGTCGGGTATCTTCGCAATCCTGCGGATACTGAGATAACCCGTTGAGACACACATCAGGGGGTATCTACGGGGGACACCATACTATCAGGTTGGGCACAAATCCCGGGGCGCGGTCGGTACAGTAGGTCGGCGTATTGCATGGTTCCCTGGGCAGCACATAACCCCGCCAAAGGCATAGAGAGAAAACGGAGGTTATTCCAGTGGTCTCCAGGGAGATCAGGACCTTAGTTCACGGGGGTCTAGCCCCTTTTTGAGTCCACCACCACTTAATCTTGGTTCGTGCCTAGCGTTCAAATAGCAAGAAAAGCAGTTCGGAGGATGTCTCCCAGTGGAATTCCCGTTTTCAACGTTCCTCAAACATTCCCAGCTTCCTGAGGCTGGAGTCTCCTGAGTAAGCGAGAAGGGAATATTCCATGGAGGCGCCCTCATCATCTAGTTCCGGTGCCTATGTCAGAACTCCCTGGCGTCGATATAGTGTCGACTTTACGAAGGCTCGTCGACGGTATACACGAGTCTTCCGACGTCCGCTGACGACGGATCAAGCGCTTATAACGCCAATCACCCTCTGGGGCATAGATTCGTAGTGTCAATGAGTAGAGAATAGTCTGAAATTCGTAGTGAGTTTCCATTGAGCTGCAAAGGCATAACTACCGACCTGGATAGTGCTGAGTACTTTTCACACTGGTCATACTTGTTGTATCGTTTGGCAGCCCAACCGTTATCTGGATGTACTCAATGTCGTACCCGGTTAGGCTCCGGAACCAGATAAATATCGAACCGCACCGATAGGGTACTAGCTACATCTGTAGCTTAACACGCCGATCTCTAATCGGGTAGATCTGTACGGCCTAGGGCGATAAAGTGCCCGTGGGTTTGGAATTCCGTCCACACAAAGTAGCGACTA"
    pointMut(s1,s2)